services:
  - type: web
    name: tasktracker-apms
    runtime: docker
    plan: free
    rootDir: backend/demo
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        value: postgres
      - key: DATABASE_PASSWORD
        sync: false
      - key: HIBERNATE_DDL_AUTO
        value: update
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_URL
        value: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
